#!/usr/bin/env python3
"""Heuristic Side Chat code-quality and AI-readability snapshot.

Dependency-free triage script for agents. It does not replace Oxfmt, Oxlint,
TypeScript, Vitest, custom governance lints, or manual review.
"""
from __future__ import annotations

import argparse
import json
import os
import re
from dataclasses import asdict, dataclass
from pathlib import Path
from typing import Iterable

CODE_EXTENSIONS = {".ts", ".tsx", ".js", ".jsx", ".mts", ".cts", ".mjs", ".cjs"}
IGNORE_DIRS = {
    ".git",
    ".hg",
    ".svn",
    ".omx",
    ".playwright-mcp",
    "node_modules",
    "dist",
    "build",
    "coverage",
    ".next",
    ".nuxt",
    ".turbo",
    ".cache",
    "out",
}
GENERATED_HINTS = ("@generated", "auto-generated", "autogenerated", "generated by", "do not edit")

FUNC_PATTERNS = [
    re.compile(r"\bfunction\s+([A-Za-z_$][\w$]*)?\s*\("),
    re.compile(
        r"\b(?:const|let|var)\s+([A-Za-z_$][\w$]*)\s*=\s*(?:async\s*)?(?:\([^)]*\)|[A-Za-z_$][\w$]*)\s*(?::[^=]+)?=>"
    ),
    re.compile(
        r"^\s*(?:public\s+|private\s+|protected\s+|static\s+|async\s+)*([A-Za-z_$][\w$]*)\s*\([^;]*\)\s*[:\w\s<>,\[\].|&?]*\{"
    ),
]
COMMENT_LINE_RE = re.compile(r"^\s*(//|/\*|\*|\*/)")
IMPORT_RE = re.compile(r"\bfrom\s+['\"]([^'\"]+)['\"]|\bimport\s*\(\s*['\"]([^'\"]+)['\"]")
CONTROL_RE = re.compile(r"\b(if|for|while|catch|switch|case)\b|\?")
CYCLO_RE = re.compile(r"\b(if|for|while|case|catch)\b|\?|&&|\|\|")

DOMAIN_TERMS = [
    "adapter",
    "activity",
    "agent",
    "ai sdk",
    "assistant",
    "boundary",
    "capability",
    "context",
    "core",
    "effect",
    "event",
    "failure",
    "manifest",
    "model",
    "profile",
    "provider",
    "protocol",
    "request",
    "runtime",
    "sequence",
    "stream",
    "tool",
    "toolcallid",
    "toolloopagent",
    "turn",
    "typed",
    "workflow",
]
ORIENTATION_WORDS = [
    "because",
    "so ",
    "so that",
    "caller",
    "widget",
    "core",
    "runtime",
    "inside",
    "outside",
    "keeps",
    "stays",
    "preserve",
    "identif",
    "before",
    "after",
    "instead",
    "allowed",
    "must",
    "must not",
]
VAGUE_NAMES = {
    "data",
    "value",
    "item",
    "items",
    "result",
    "results",
    "input",
    "output",
    "state",
    "part",
    "payload",
    "handler",
    "manager",
    "gen",
    "params",
    "options",
}

SMELL_PATTERNS = {
    "explicit_any": re.compile(r"(?::\s*any\b|\bas\s+any\b|<\s*any\s*>|\bArray\s*<\s*any\s*>|\bPromise\s*<\s*any\s*>|\bRecord\s*<\s*string\s*,\s*any\s*>)"),
    "double_assertion": re.compile(r"\bas\s+unknown\s+as\b|\bas\s+any\s+as\b"),
    "non_null_assertion_hint": re.compile(r"(?<![=!])!\s*(?:\.|\[|[;,):])"),
    "ts_ignore": re.compile(r"@ts-ignore"),
    "eslint_disable": re.compile(r"eslint-disable"),
    "raw_throw": re.compile(r"\bthrow\s+new\s+|\bthrow\s+[^;]+"),
    "json_parse": re.compile(r"\bJSON\.parse\s*\("),
    "process_env": re.compile(r"\bprocess\.env\."),
    "fetch_or_socket": re.compile(r"\bfetch\s*\(|new\s+WebSocket\b|new\s+EventSource\b"),
    "nested_ternary_hint": re.compile(r"\?[^:\n]+:[^\n]+\?"),
    "use_effect": re.compile(r"\buse(?:Layout)?Effect\s*\("),
    "object_spread": re.compile(r"\.\.\."),
    "callback_density_hint": re.compile(r"=>|\.map\s*\(|\.flatMap\s*\(|\.filter\s*\(|\.reduce\s*\(|\.then\s*\("),
    "effect_stream_terms": re.compile(r"\bEffect\.|\bStream\.|\bEffect\.gen\b|\bStream\.unwrap\b"),
    "ai_sdk_terms": re.compile(r"\bToolLoopAgent\b|\bTextStreamPart\b|\b@ai-sdk/|\bfrom ['\"]ai['\"]"),
    "deep_callback_terms": re.compile(r"\bflatMap\b|\breduce\b|\bunwrap\b|\bgen\b|\bcatchCauseIf\b|\btryPromise\b"),
}


@dataclass
class FunctionMetric:
    file: str
    name: str
    start_line: int
    end_line: int
    lines: int
    cyclomatic: int
    cognitive: int
    max_nesting: int
    vague_name_hits: int
    effect_stream_hits: int
    ai_sdk_hits: int


@dataclass
class CommentMetric:
    file: str
    start_line: int
    lines: int
    domain_term_hits: int
    orientation_hits: int
    text_preview: str


@dataclass
class FileMetric:
    file: str
    lines: int
    code_lines: int
    import_count: int
    parent_relative_imports: int
    smell_counts: dict[str, int]
    max_cognitive: int
    max_cyclomatic: int
    max_function_lines: int
    vague_name_hits: int
    domain_term_hits: int
    comment_context_debt: int
    generated: bool


def iter_code_files(root: Path, max_files: int | None = None) -> Iterable[Path]:
    count = 0
    for dirpath, dirnames, filenames in os.walk(root):
        dirnames[:] = [d for d in dirnames if d not in IGNORE_DIRS and not d.startswith("node_modules")]
        for filename in filenames:
            path = Path(dirpath) / filename
            if path.suffix in CODE_EXTENSIONS:
                yield path
                count += 1
                if max_files is not None and count >= max_files:
                    return


def read_text(path: Path) -> str:
    try:
        return path.read_text(encoding="utf-8")
    except UnicodeDecodeError:
        return path.read_text(encoding="utf-8", errors="ignore")


def is_generated(text: str) -> bool:
    head = text[:2000].lower()
    return any(hint in head for hint in GENERATED_HINTS)


def count_code_lines(lines: list[str]) -> int:
    return sum(1 for line in lines if line.strip() and not COMMENT_LINE_RE.match(line))


def strip_strings(line: str) -> str:
    line = re.sub(r"`(?:\\.|[^`])*`", "``", line)
    line = re.sub(r"'(?:\\.|[^'])*'", "''", line)
    line = re.sub(r'"(?:\\.|[^"])*"', '""', line)
    return line


def find_function_name(line: str) -> str | None:
    for pattern in FUNC_PATTERNS:
        match = pattern.search(line)
        if not match:
            continue
        name = match.group(1) if match.lastindex else None
        if name in {"if", "for", "while", "switch", "catch", "function"}:
            return None
        return name or "<anonymous>"
    return None


def compute_complexity(block_lines: list[str]) -> tuple[int, int, int]:
    cyclomatic = 1
    cognitive = 0
    nesting = 0
    max_nesting = 0

    for raw_line in block_lines:
        line = strip_strings(raw_line)
        stripped = line.strip()
        if not stripped or COMMENT_LINE_RE.match(stripped):
            continue

        leading = re.match(r"^\s*\}+", line)
        if leading:
            nesting = max(0, nesting - leading.group(0).count("}"))

        cyclomatic += len(CYCLO_RE.findall(line))
        for _ in CONTROL_RE.findall(line):
            cognitive += 1 + min(nesting, 4)

        bool_ops = len(re.findall(r"&&|\|\|", line))
        if bool_ops > 1:
            cognitive += bool_ops - 1

        nesting = max(0, nesting + line.count("{") - line.count("}"))
        max_nesting = max(max_nesting, nesting)

    return cyclomatic, cognitive, max_nesting


def count_vague_names(text: str) -> int:
    count = 0
    for name in VAGUE_NAMES:
        count += len(re.findall(rf"\b{name}\b", text))
    return count


def count_domain_terms(text: str) -> int:
    lower = text.lower()
    return sum(lower.count(term) for term in DOMAIN_TERMS)


def extract_functions(rel: str, text: str) -> list[FunctionMetric]:
    lines = text.splitlines()
    functions: list[FunctionMetric] = []
    i = 0
    while i < len(lines):
        name = find_function_name(lines[i])
        if not name:
            i += 1
            continue

        start = i
        brace_balance = strip_strings(lines[i]).count("{") - strip_strings(lines[i]).count("}")
        end = i

        if "=>" in lines[i] and "{" not in lines[i]:
            end = i
        else:
            j = i + 1
            while j < len(lines) and (brace_balance > 0 or j == i + 1):
                brace_balance += strip_strings(lines[j]).count("{") - strip_strings(lines[j]).count("}")
                end = j
                if brace_balance <= 0:
                    break
                j += 1

        block = lines[start : end + 1]
        block_text = "\n".join(block)
        cyclomatic, cognitive, max_nesting = compute_complexity(block)
        functions.append(
            FunctionMetric(
                file=rel,
                name=name,
                start_line=start + 1,
                end_line=end + 1,
                lines=count_code_lines(block),
                cyclomatic=cyclomatic,
                cognitive=cognitive,
                max_nesting=max_nesting,
                vague_name_hits=count_vague_names(block_text),
                effect_stream_hits=len(SMELL_PATTERNS["effect_stream_terms"].findall(block_text)),
                ai_sdk_hits=len(SMELL_PATTERNS["ai_sdk_terms"].findall(block_text)),
            )
        )
        i = max(end + 1, i + 1)
    return functions


def extract_block_comments(rel: str, text: str) -> list[CommentMetric]:
    comments: list[CommentMetric] = []
    lines = text.splitlines()
    i = 0
    while i < len(lines):
        if "/**" not in lines[i] and "/*" not in lines[i]:
            i += 1
            continue
        start = i
        block = [lines[i]]
        while i < len(lines) and "*/" not in lines[i]:
            i += 1
            if i < len(lines):
                block.append(lines[i])
        raw = "\n".join(block)
        cleaned = re.sub(r"^\s*/\*\*?", "", raw)
        cleaned = re.sub(r"\*/\s*$", "", cleaned)
        cleaned = re.sub(r"^\s*\* ?", "", cleaned, flags=re.MULTILINE).strip()
        domain_hits = count_domain_terms(cleaned)
        orientation_hits = sum(cleaned.lower().count(word) for word in ORIENTATION_WORDS)
        comments.append(
            CommentMetric(
                file=rel,
                start_line=start + 1,
                lines=len(block),
                domain_term_hits=domain_hits,
                orientation_hits=orientation_hits,
                text_preview=" ".join(cleaned.split())[:180],
            )
        )
        i += 1
    return comments


def analyze_file(root: Path, path: Path) -> tuple[FileMetric, list[FunctionMetric], list[CommentMetric]]:
    rel = path.relative_to(root).as_posix()
    text = read_text(path)
    lines = text.splitlines()
    generated = is_generated(text)
    functions = [] if generated else extract_functions(rel, text)
    comments = [] if generated else extract_block_comments(rel, text)

    imports = [m.group(1) or m.group(2) for m in IMPORT_RE.finditer(text)]
    smell_counts = {name: len(pattern.findall(text)) for name, pattern in SMELL_PATTERNS.items()}
    comment_context_debt = sum(1 for c in comments if c.domain_term_hits >= 4 and c.orientation_hits <= 1)

    return (
        FileMetric(
            file=rel,
            lines=len(lines),
            code_lines=count_code_lines(lines),
            import_count=len(imports),
            parent_relative_imports=sum(1 for imp in imports if imp.startswith("../")),
            smell_counts=smell_counts,
            max_cognitive=max((f.cognitive for f in functions), default=0),
            max_cyclomatic=max((f.cyclomatic for f in functions), default=0),
            max_function_lines=max((f.lines for f in functions), default=0),
            vague_name_hits=count_vague_names(text),
            domain_term_hits=count_domain_terms(text),
            comment_context_debt=comment_context_debt,
            generated=generated,
        ),
        functions,
        comments,
    )


def file_score(metric: FileMetric) -> int:
    smells = metric.smell_counts
    return (
        metric.max_cognitive * 5
        + metric.max_cyclomatic * 3
        + metric.max_function_lines
        + min(metric.code_lines // 15, 60)
        + smells["explicit_any"] * 5
        + smells["double_assertion"] * 10
        + smells["ts_ignore"] * 10
        + smells["eslint_disable"] * 4
        + smells["raw_throw"] * 2
        + smells["nested_ternary_hint"] * 5
        + smells["use_effect"] * 3
        + smells["callback_density_hint"]
        + smells["effect_stream_terms"] * 3
        + smells["ai_sdk_terms"] * 4
        + smells["deep_callback_terms"] * 3
        + metric.comment_context_debt * 8
        + min(metric.vague_name_hits // 4, 40)
    )


def function_score(fn: FunctionMetric) -> int:
    return (
        fn.cognitive * 5
        + fn.cyclomatic * 3
        + fn.lines
        + fn.max_nesting * 4
        + fn.effect_stream_hits * 4
        + fn.ai_sdk_hits * 5
        + min(fn.vague_name_hits, 20)
    )


def build_report(root: Path, max_files: int | None) -> dict:
    files: list[FileMetric] = []
    functions: list[FunctionMetric] = []
    comments: list[CommentMetric] = []

    for path in iter_code_files(root, max_files):
        file_metric, file_functions, file_comments = analyze_file(root, path)
        files.append(file_metric)
        functions.extend(file_functions)
        comments.extend(file_comments)

    smell_totals = {name: 0 for name in SMELL_PATTERNS}
    for metric in files:
        for name, count in metric.smell_counts.items():
            smell_totals[name] += count

    risky_comments = sorted(
        [c for c in comments if c.domain_term_hits >= 4 and c.orientation_hits <= 1],
        key=lambda c: (c.domain_term_hits, c.lines),
        reverse=True,
    )[:30]

    top_files = []
    for metric in sorted(files, key=file_score, reverse=True)[:35]:
        top_files.append(
            {
                "score": file_score(metric),
                "file": metric.file,
                "code_lines": metric.code_lines,
                "max_cognitive": metric.max_cognitive,
                "max_cyclomatic": metric.max_cyclomatic,
                "max_function_lines": metric.max_function_lines,
                "comment_context_debt": metric.comment_context_debt,
                "signals": {k: v for k, v in metric.smell_counts.items() if v},
            }
        )

    top_functions = [
        asdict(fn)
        | {"score": function_score(fn)}
        for fn in sorted(functions, key=function_score, reverse=True)[:50]
    ]

    return {
        "summary": {
            "root": root.as_posix(),
            "files_scanned": len(files),
            "functions_detected": len(functions),
            "comments_detected": len(comments),
            "generated_files_skipped_for_functions": sum(1 for f in files if f.generated),
            "total_code_lines": sum(f.code_lines for f in files),
        },
        "smell_totals": smell_totals,
        "top_files": top_files,
        "top_functions": top_functions,
        "comment_context_debt_candidates": [asdict(c) for c in risky_comments],
        "files": [asdict(f) for f in files],
    }


def write_markdown(report: dict, output: Path) -> None:
    lines: list[str] = []
    lines.append("# Side Chat Quality Snapshot")
    lines.append("")
    lines.append("Heuristic scan for code-shape and AI-readability triage. Do not treat this as authoritative; use repo checks and manual review.")
    lines.append("")
    lines.append("## Summary")
    lines.append("")
    for key, value in report["summary"].items():
        lines.append(f"- **{key}**: `{value}`")
    lines.append("")

    lines.append("## Top file hotspots")
    lines.append("")
    lines.append("| Score | File | Lines | Max cog | Max cyc | Max fn lines | Comment debt | Signals |")
    lines.append("|---:|---|---:|---:|---:|---:|---:|---|")
    for item in report["top_files"]:
        signals = ", ".join(f"{k}={v}" for k, v in item["signals"].items() if v) or "-"
        lines.append(
            f"| {item['score']} | `{item['file']}` | {item['code_lines']} | {item['max_cognitive']} | {item['max_cyclomatic']} | {item['max_function_lines']} | {item['comment_context_debt']} | {signals} |"
        )
    lines.append("")

    lines.append("## Top function hotspots")
    lines.append("")
    lines.append("| Score | Cog | Cyc | Lines | Nest | Function | Signals |")
    lines.append("|---:|---:|---:|---:|---:|---|---|")
    for fn in report["top_functions"]:
        signals = []
        if fn["effect_stream_hits"]:
            signals.append(f"effect/stream={fn['effect_stream_hits']}")
        if fn["ai_sdk_hits"]:
            signals.append(f"ai-sdk={fn['ai_sdk_hits']}")
        if fn["vague_name_hits"]:
            signals.append(f"vague-names={fn['vague_name_hits']}")
        signal_text = ", ".join(signals) or "-"
        lines.append(
            f"| {fn['score']} | {fn['cognitive']} | {fn['cyclomatic']} | {fn['lines']} | {fn['max_nesting']} | `{fn['file']}:{fn['start_line']}` `{fn['name']}` | {signal_text} |"
        )
    lines.append("")

    lines.append("## Comment context-debt candidates")
    lines.append("")
    lines.append("These comments contain several Side Chat domain terms but few local orientation words. Inspect manually before editing.")
    lines.append("")
    lines.append("| File | Line | Terms | Orientation | Preview |")
    lines.append("|---|---:|---:|---:|---|")
    for comment in report["comment_context_debt_candidates"]:
        preview = comment["text_preview"].replace("|", "\\|")
        lines.append(
            f"| `{comment['file']}` | {comment['start_line']} | {comment['domain_term_hits']} | {comment['orientation_hits']} | {preview} |"
        )
    lines.append("")

    lines.append("## Signal totals")
    lines.append("")
    for key, value in report["smell_totals"].items():
        if value:
            lines.append(f"- **{key}**: {value}")
    lines.append("")
    lines.append("## How to use this")
    lines.append("")
    lines.append("Start with files that are both high-scoring and likely to be edited. Then inspect manually with the repo gate: Oxfmt, Oxlint, TypeScript, tests, custom governance, and the AI-readable simplicity rules. Do not refactor solely to improve this report.")
    output.write_text("\n".join(lines), encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser(description="Side Chat heuristic code-quality snapshot")
    parser.add_argument("root", nargs="?", default=".", help="Repository root or folder to scan")
    parser.add_argument("--json", dest="json_output", help="Write full JSON report")
    parser.add_argument("--markdown", dest="markdown_output", help="Write Markdown report")
    parser.add_argument("--max-files", type=int, default=None, help="Limit files scanned")
    args = parser.parse_args()

    root = Path(args.root).resolve()
    if not root.exists():
        raise SystemExit(f"Root does not exist: {root}")

    report = build_report(root, args.max_files)
    if args.json_output:
        Path(args.json_output).write_text(json.dumps(report, indent=2), encoding="utf-8")
    if args.markdown_output:
        write_markdown(report, Path(args.markdown_output))
    if not args.json_output and not args.markdown_output:
        print(json.dumps({"summary": report["summary"], "top_files": report["top_files"][:10]}, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
