import { SCRIPTED_PROVIDER } from "#config/providers/scripted-provider-config";

export const PROVIDER_SCRIPT_MODE = {
  COMPLETE: SCRIPTED_PROVIDER.MODELS.COMPLETE.MODEL_ID,
  TITLE: SCRIPTED_PROVIDER.MODELS.TITLE.MODEL_ID,
  BLOCK: SCRIPTED_PROVIDER.MODELS.BLOCK.MODEL_ID,
  CRASH_RECOVERY: SCRIPTED_PROVIDER.MODELS.CRASH_RECOVERY.MODEL_ID,
  HAPPY: SCRIPTED_PROVIDER.MODELS.HAPPY.MODEL_ID,
  MULTI_STEP: SCRIPTED_PROVIDER.MODELS.MULTI_STEP.MODEL_ID,
  EMPTY: SCRIPTED_PROVIDER.MODELS.EMPTY.MODEL_ID,
  STEP_LIMIT: SCRIPTED_PROVIDER.MODELS.STEP_LIMIT.MODEL_ID,
  REASONING_ONLY: SCRIPTED_PROVIDER.MODELS.REASONING_ONLY.MODEL_ID,
  CLIENT_TOOL: SCRIPTED_PROVIDER.MODELS.CLIENT_TOOL.MODEL_ID,
  NATIVE_APPROVAL_GAP: SCRIPTED_PROVIDER.MODELS.NATIVE_APPROVAL_GAP.MODEL_ID,
  CANCEL_BEFORE_FIRST: SCRIPTED_PROVIDER.MODELS.CANCEL_BEFORE_FIRST.MODEL_ID,
  CANCEL_MID: SCRIPTED_PROVIDER.MODELS.CANCEL_MID.MODEL_ID,
  ERROR_BEFORE: SCRIPTED_PROVIDER.MODELS.ERROR_BEFORE.MODEL_ID,
  ERROR_MID: SCRIPTED_PROVIDER.MODELS.ERROR_MID.MODEL_ID,
} as const;

export type ProviderScriptMode = (typeof PROVIDER_SCRIPT_MODE)[keyof typeof PROVIDER_SCRIPT_MODE];

const PROVIDER_SCRIPT_MODES = new Set<string>(Object.values(PROVIDER_SCRIPT_MODE));

export const LATE_CONTENT_MARKER = "late-content-after-abort";
export const CLIENT_TOOL_PRIVATE_RESULT_MARKER = "private-result-must-not-enter-stream";

export function isProviderScriptMode(value: string): value is ProviderScriptMode {
  return PROVIDER_SCRIPT_MODES.has(value);
}
