// AUTO-GENERATED from design_widget.html token tables (the design spec). Do not hand-edit;
// re-extract from the design file if tokens change. Rows are tab-delimited to keep source governance readable.
export type DesignToken = {
  readonly token: string;
  readonly resolvesTo: string;
  readonly property: string;
  readonly controls: string;
  readonly component: string;
};

const TOKEN_ROWS = [
  "--panel-bg	var(--card)	background	Panel surface fill	shell",
  "--panel-border	var(--border)	border-color	1px hairline frame	shell",
  "--panel-radius	var(--radius-xl)	border-radius	Outer corner (clips both columns)	shell",
  "--panel-shadow	var(--shadow-panel)	box-shadow	Floating elevation	shell",
  "--header-px	var(--space-4)	padding-inline	Header horizontal padding	shell",
  "--header-py	var(--space-3)	padding-block	Header vertical padding	shell",
  "--header-border	var(--border)	border-bottom	Header / body divider	shell",
  "--header-h	3.25rem	height	Header & rail top-zone height (alignment anchor)	shell",
  "--header-title-size	var(--text-md)	font-size	Title text size	shell",
  "--agent-mark-fg	var(--primary)	fill / stroke	Glyph mark	shell",
  "--agent-mark-bg	var(--accent)	background	Glyph tile fill	shell",
  "--agent-mark-radius	var(--radius-md)	border-radius	Glyph tile corner	shell",
  "--iconbtn-size	var(--size-control)	width / height	Action button box	button",
  "--iconbtn-fg	var(--muted-foreground)	color	Action icon color	button",
  "--iconbtn-bg-hover	var(--accent)	background	Action hover fill	button",
  "--message-user-bg	var(--row-bg-active, var(--accent))	background	User bubble fill	message",
  "--message-user-fg	var(--foreground)	color	User bubble text	message",
  "--message-user-size	var(--text-md)	font-size	Bubble text size	message",
  "--message-user-radius	var(--radius-lg)	border-radius	Bubble corners	message",
  "--message-user-radius-tail	var(--radius-sm)	border-bottom-right-radius	Speech tail	message",
  "--message-user-px	var(--space-4)	padding-inline	Bubble x-padding	message",
  "--message-user-py	var(--space-2-5)	padding-block	Bubble y-padding	message",
  "--message-user-max	82%	max-width	Bubble max width	message",
  "--message-assistant-fg	var(--card-foreground)	color	Assistant body text	message",
  "--message-assistant-size	var(--text-md)	font-size	Assistant text size	message",
  "--message-assistant-leading	var(--leading-relaxed)	line-height	Assistant line-height	message",
  "--action-fg	var(--muted-foreground)	color	Copy / retry rest	message-actions",
  "--action-fg-hover	var(--foreground)	color	Hover text	message-actions",
  "--action-bg-hover	var(--accent)	background	Hover fill	message-actions",
  "--action-radius	var(--radius-sm)	border-radius	Button corner	message-actions",
  "--action-size	var(--text-xs)	font-size	Label size	message-actions",
  "--action-copied-fg	var(--success)	color	Copied confirmation	message-actions",
  "--composer-bg	var(--background)	background	Field fill	composer",
  "--composer-border	var(--input)	border-color	Resting border	composer",
  "--composer-ring	var(--ring)	box-shadow (focus)	Focus ring color	composer",
  "--composer-radius	var(--radius-xl)	border-radius	Field corner	composer",
  "--composer-shadow	var(--shadow-card)	box-shadow	Resting elevation	composer",
  "--composer-px	var(--space-5)	padding-inline	Text x-padding	composer",
  "--composer-py	var(--space-4)	padding-block	Text y-padding	composer",
  "--send-size	var(--size-send)	width / height	Send button box	composer",
  "--send-radius	var(--radius-md)	border-radius	Send corner	composer",
  "--send-bg-armed	var(--primary)	background	Send fill (armed)	composer",
  "--send-fg-armed	var(--primary-foreground)	color	Send icon (armed)	composer",
  "--send-bg-idle	var(--muted)	background	Send fill (idle)	composer",
  "--send-fg-idle	var(--muted-foreground)	color	Send icon (idle)	composer",
  "--context-ring-track	var(--border)	stroke	Context ring track	composer",
  "--context-ring-indicator	var(--muted-foreground)	stroke	Context ring progress	composer",
  "--btn-radius	var(--radius-md)	border-radius	All button corners	button",
  "--btn-px	var(--space-4)	padding-inline	Button x-padding	button",
  "--btn-py	var(--space-2)	padding-block	Button y-padding	button",
  "--btn-size	var(--text-base)	font-size	Button label size	button",
  "--btn-primary-bg	var(--primary)	background	Primary fill	button",
  "--btn-primary-fg	var(--primary-foreground)	color	Primary text	button",
  "--btn-secondary-bg	var(--secondary)	background	Secondary fill	button",
  "--btn-secondary-fg	var(--secondary-foreground)	color	Secondary text	button",
  "--btn-secondary-border	var(--border)	border-color	Secondary border	button",
  "--btn-ghost-fg	var(--foreground)	color	Ghost text	button",
  "--btn-ghost-bg-hover	var(--accent)	background	Ghost hover fill	button",
  "--iconbtn-radius	var(--radius-md)	border-radius	Icon button corner	button",
  "--switch-track-on	var(--primary)	background	Track when on	switch",
  "--switch-track-off	var(--input)	background	Track when off	switch",
  "--switch-knob	oklch(0.99 0 0)	background	Sliding knob	switch",
  "--switch-w	30px	width	Track width	switch",
  "--switch-h	18px	height	Track height	switch",
  "--menu-bg	var(--popover)	background	Menu surface	menu",
  "--menu-fg	var(--popover-foreground)	color	Menu text	menu",
  "--menu-border	var(--border)	border-color	Menu frame	menu",
  "--menu-radius	var(--radius-xl)	border-radius	Menu corner	menu",
  "--menu-shadow	var(--shadow-popover)	box-shadow	Menu elevation	menu",
  "--menu-pad	var(--space-1-5)	padding	Menu inner padding	menu",
  "--menu-section-label	var(--muted-foreground)	color	Group overline (Tools...)	menu",
  "--menu-item-radius	var(--radius-md)	border-radius	Item corner	menu",
  "--menu-item-bg-hover	var(--accent)	background	Item hover / active fill	menu",
  "--menu-item-px	var(--space-2-5)	padding-inline	Item x-padding	menu",
  "--menu-item-py	var(--space-2)	padding-block	Item y-padding	menu",
  "--menu-item-check	var(--primary)	color	Active check color	menu",
  "--model-search-border	var(--border)	border-bottom	Search field divider	model-selector",
  "--model-icon-bg	var(--muted)	background	Row avatar fill	model-selector",
  "--model-icon-border	var(--border)	border-color	Row avatar frame	model-selector",
  "--model-icon-fg	var(--muted-foreground)	color	Row avatar glyph	model-selector",
  "--model-name-fg	var(--popover-foreground)	color	Model name	model-selector",
  "--model-desc-fg	var(--muted-foreground)	color	Model description	model-selector",
  "--seg-bg	var(--muted)	background	Thinking control track	segmented",
  "--seg-item-active-bg	var(--background)	background	Selected level fill	segmented",
  "--seg-item-active-fg	var(--foreground)	color	Selected level text	segmented",
  "--seg-item-fg	var(--muted-foreground)	color	Unselected level text	segmented",
  "--seg-item-radius	calc(var(--radius-md) - 3px)	border-radius	Level pill corner	segmented",
  "--rail-bg	var(--sidebar)	background	Rail surface	sidebar-rail",
  "--rail-fg	var(--sidebar-foreground)	color	Rail text	sidebar-rail",
  "--rail-border	var(--sidebar-border)	border-right	Seam against main column	sidebar-rail",
  "--rail-width	var(--size-sidebar)	width	Rail width	sidebar-rail",
  "--rail-item-radius	var(--radius-md)	border-radius	Row corner	sidebar-rail",
  "--rail-item-bg-active	var(--row-bg-active)	background	Active row fill	sidebar-rail",
  "--rail-item-bg-hover	var(--row-bg-hover)	background	Hover row fill	sidebar-rail",
  "--seg-radius	var(--radius-md)	border-radius	Track corner	segmented",
  "--seg-pad	3px	padding	Track inset around items	segmented",
  "--seg-item-size	var(--text-xs)	font-size	Item label size	segmented",
  "--row-px	var(--space-2-5)	padding-inline	Row x-padding (10px)	row",
  "--row-py	var(--space-2)	padding-block	Row y-padding (8px)	row",
  "--row-gap	var(--space-2-5)	gap	Media / text / trailing gap	row",
  "--row-radius	var(--radius-md)	border-radius	Row corner	row",
  "--row-bg-hover	var(--accent)	background	Hover fill	row",
  "--row-bg-active	var(--accent)	background	Selected fill	row",
  "--row-title-size	var(--text-sm)	font-size	Title size	row",
  "--row-title-weight	var(--weight-medium)	font-weight	Title weight	row",
  "--row-title-fg	var(--foreground)	color	Title color	row",
  "--row-subtitle-size	var(--text-xs)	font-size	Subtitle size	row",
  "--row-subtitle-fg	var(--muted-foreground)	color	Subtitle color	row",
  "--media-size	1.625rem	width / height	Avatar box (26px)	media",
  "--media-radius	var(--radius-md)	border-radius	Avatar corner	media",
  "--media-bg	var(--muted)	background	Avatar fill	media",
  "--media-border	var(--border)	border-color	Avatar frame	media",
  "--media-fg	var(--muted-foreground)	color	Avatar glyph	media",
  "--title-size	var(--text-md)	font-size	Panel title (15px)	field",
  "--title-weight	var(--weight-semibold)	font-weight	Panel title weight	field",
  "--title-fg	var(--foreground)	color	Panel title color	field",
  "--label-size	var(--text-sm)	font-size	Control label (13px)	field",
  "--label-weight	var(--weight-semibold)	font-weight	Control label weight	field",
  "--label-fg	var(--foreground)	color	Control label color	field",
  "--hint-size	var(--text-xs)	font-size	Helper text (12px)	field",
  "--hint-fg	var(--muted-foreground)	color	Helper text color	field",
  "--field-bg	var(--background)	background	Input / textarea fill	field",
  "--field-border	var(--input)	border-color	Field border	field",
  "--field-ring	var(--ring)	box-shadow (focus)	Field focus ring	field",
  "--field-radius	var(--radius-md)	border-radius	Field corner	field",
  "--field-px	var(--space-3)	padding-inline	Field x-padding	field",
  "--field-py	var(--space-2-5)	padding-block	Field y-padding	field",
  "--field-size	var(--text-sm)	font-size	Field text	field",
  "--select-border	var(--input)	border-color	Select border	select",
  "--select-radius	var(--radius-md)	border-radius	Select corner	select",
  "--select-icon	var(--muted-foreground)	color	Select chevrons	select",
  "--convo-item-px	var(--space-2-5)	padding-inline	Item x-padding (10px)	conversation-item",
  "--convo-item-py	var(--space-2)	padding-block	Item y-padding (8px)	conversation-item",
  "--convo-item-gap	2px	gap	Title \\\\u2194 timestamp gap	conversation-item",
  "--convo-item-radius	var(--radius-md)	border-radius	Item corner	conversation-item",
  "--convo-item-bg-active	var(--row-bg-active)	background	Selected row fill	conversation-item",
  "--convo-item-bg-hover	var(--row-bg-hover)	background	Hover row fill	conversation-item",
  "--convo-title-size	var(--text-sm)	font-size	Title (13px)	conversation-item",
  "--convo-title-weight	var(--weight-medium)	font-weight	Title weight (500)	conversation-item",
  "--convo-title-fg	var(--sidebar-foreground)	color	Title color	conversation-item",
  "--convo-subtitle-size	var(--text-xs)	font-size	Timestamp (12px)	conversation-item",
  "--convo-subtitle-fg	var(--muted-foreground)	color	Timestamp color	conversation-item",
  "--convo-indicator	var(--primary)	background	Active row dot	conversation-item",
  "--rail-pad	var(--space-3)	padding	Rail & list outer padding (12px)	sidebar-rail",
  "--rail-newchat-h	var(--header-h)	height	New-chat zone - aligns to header	sidebar-rail",
  "--rail-list-gap	1px	gap	Between items	sidebar-rail",
  "--rail-group-gap	var(--space-2)	gap	Between groups (8px)	sidebar-rail",
  "--group-label-size	var(--text-2xs)	font-size	Overline (11px)	conversation-grouping",
  "--group-label-fg	var(--muted-foreground)	color	Overline color	conversation-grouping",
  "--group-label-pt	var(--space-3)	padding-top	Space above overline (12px)	conversation-grouping",
  "--group-label-pb	var(--space-1-5)	padding-bottom	Space below overline (6px)	conversation-grouping",
  "--group-label-px	var(--space-2)	padding-inline	Overline indent (8px)	conversation-grouping",
  "--reason-rule	var(--border)	border-left	Left timeline rule	reasoning",
  "--reason-text-fg	var(--muted-foreground)	color	Thought text	reasoning",
  "--reason-text-size	var(--text-sm)	font-size	Thought size	reasoning",
  "--reason-label-fg	var(--muted-foreground)	color	Header label	reasoning",
  "--tool-running-fg	var(--primary)	color	Spinner color	tool-row",
  "--tool-done-fg	var(--success)	color	Done check color	tool-row",
  "--tool-label-fg	var(--foreground)	color	Tool name color	tool-row",
  "--tool-label-size	var(--text-sm)	font-size	Tool name size	tool-row",
  "--error-bg	var(--muted)	background	Notice surface	error-notice",
  "--error-border	var(--border)	border-color	Notice frame	error-notice",
  "--error-radius	var(--radius-lg)	border-radius	Notice corner	error-notice",
  "--error-icon-fg	mix(--destructive, --muted-foreground)	color	Alert glyph	error-notice",
  "--error-text-fg	var(--foreground)	color	Notice text	error-notice",
  "--error-btn-bg	var(--secondary)	background	Retry secondary button fill	error-notice",
  "--error-btn-fg	var(--secondary-foreground)	color	Retry secondary button text	error-notice",
  "--error-btn-border	var(--border)	border-color	Retry button frame	error-notice",
  "--badge-bg	var(--secondary)	background	Badge fill	badge",
  "--badge-fg	var(--secondary-foreground)	color	Badge text	badge",
  "--badge-radius	999px	border-radius	Pill corner	badge",
  "--badge-size	var(--text-xs)	font-size	Badge text size	badge",
  "--suggestion-fg	var(--card-foreground)	color	Suggestion text	badge",
  "--suggestion-bg-hover	var(--accent)	background	Suggestion hover fill	badge",
  "--suggestion-radius	var(--radius-md)	border-radius	Suggestion corner	badge",
  "--scrollarea-size	0.5rem	width	Overlay thumb width	scroll-area",
  "--scrollarea-thumb	var(--border)	background	Thumb at rest	scroll-area",
  "--scrollarea-thumb-hover	var(--muted-foreground)	background	Thumb while dragging	scroll-area",
  "--scrollarea-radius	9999px	border-radius	Fully-rounded thumb	scroll-area",
  "--settings-nav-w	var(--size-sidebar)	width	Group rail width; matches chat rail	settings",
  "--settings-nav-bg	var(--sidebar)	background	Group rail surface	settings",
  "--settings-nav-border	var(--sidebar-border)	border-right	Rail / content seam	settings",
  "--settings-item-active-bg	var(--convo-item-bg-active)	background	Active group row	settings",
  "--settings-item-hover-bg	var(--convo-item-bg-hover)	background	Hover group row	settings",
  "--settings-item-title-fg	var(--convo-title-fg)	color	Group row title	settings",
  "--settings-item-desc-fg	var(--convo-subtitle-fg)	color	Group row description	settings",
  "--settings-item-indicator	var(--convo-indicator)	background	Active group dot	settings",
  "--settings-item-px	var(--space-2-5)	padding-inline	Group row x-padding	settings",
  "--settings-item-py	var(--space-2)	padding-block	Group row y-padding	settings",
  "--settings-content-pad	var(--space-5)	padding	Content padding (20px)	settings",
  "--settings-field-bg	var(--background)	background	Input / textarea fill	settings",
  "--settings-field-border	var(--input)	border-color	Field border	settings",
  "--settings-field-radius	var(--radius-md)	border-radius	Field corner	settings",
  "--settings-label-size	var(--text-sm)	font-size	Field label	settings",
  "--settings-hint-fg	var(--muted-foreground)	color	Helper text	settings",
] as const;

const parseTokenRow = (row: string): DesignToken => {
  const [token, resolvesTo, property, controls, component] = row.split("\t");
  if (!token || !resolvesTo || !property || !controls || component === undefined) {
    throw new Error(`Invalid design token row: ${row}`);
  }
  return { token, resolvesTo, property, controls, component };
};

export const designTokens: readonly DesignToken[] = TOKEN_ROWS.map(parseTokenRow);

export const tokensForComponent = (id: string): readonly DesignToken[] =>
  designTokens.filter((t) => t.component === id);
