import type {
  AuthContext,
  ObservabilitySinkPort,
  StreamChatPorts,
} from "@side-chat/partner-ai-core";
import type { SidechatStreamEvent } from "@side-chat/chat-protocol";
import type { TurnEventNotificationSource } from "@side-chat/db";
import { Effect, Exit, Queue, Scope, Stream } from "effect";
import { recordResumableObservation } from "./turn-observability.js";

/**
 * Local fan-out capacity per subscriber before the queue starts dropping.
 *
 * The queue is a low-latency hint, never the source of truth: a subscriber that
 * lags past this window simply drops queued signals and re-syncs from the durable
 * log on its safety poll. So a small bound is safe and keeps a stuck reader from
 * pinning unbounded memory.
 */
const SUBSCRIBER_QUEUE_CAPACITY = 256;

/**
 * One subscriber's live feed into the subscription stream.
 *
 * `events` is a dropping queue of events the dispatcher fanned out after the
 * subscriber registered; `release` removes the subscriber from its turn's
 * fan-out (and tears the fan-out down when it was the last one).
 */
export type TurnEventSubscription = {
  readonly events: Queue.Dequeue<SidechatStreamEvent>;
  readonly release: () => Promise<void>;
};

/**
 * Per-instance fan-out of durable turn events to local SSE subscribers.
 *
 * The dispatcher is the local half of the cross-instance transport: the durable
 * log is the source of truth, Postgres `NOTIFY` (via the db notification source)
 * decides *when* to read, and this object turns each signal into a read of the
 * new rows plus a fan-out to every local subscriber of that turn. A reconnect can
 * land on any instance, so a subscriber here may be watching a turn generated by
 * a different instance — that is expected and works because both read the same
 * log.
 */
export type TurnEventDispatcher = {
  /**
   * Register a subscriber for one turn before any replay read.
   *
   * Registering first is the missed-notify guard: from this point the subscriber
   * receives every fanned-out event, so a caller can safely replay the log and
   * then drain this queue without a gap.
   */
  readonly subscribe: (input: {
    readonly assistantTurnId: string;
    readonly authContext: AuthContext;
  }) => Promise<TurnEventSubscription>;
  /** Interrupt the listener and release the dispatcher scope (shutdown). */
  readonly shutdown: () => Promise<void>;
};

export type TurnEventDispatcherDependencies = {
  readonly ports: StreamChatPorts;
  readonly notificationSource: TurnEventNotificationSource;
  /** Optional telemetry sink; subscriber attach/detach and live count are recorded. */
  readonly observability?: ObservabilitySinkPort | undefined;
};

/**
 * Mutable per-turn fan-out state shared by the listener and subscribers.
 *
 * `highWaterMark` is the highest sequence already fanned out, so a notify only
 * reads rows past it. `authContext` is captured from the first subscriber so the
 * dispatcher can read the workspace-scoped log; notifications carry only ids.
 */
type TurnFanout = {
  readonly authContext: AuthContext;
  highWaterMark: number;
  readonly subscribers: Set<Queue.Queue<SidechatStreamEvent>>;
};

/**
 * Build the dispatcher on a long-lived scope and start its single listener.
 *
 * The scope and listener fiber are created eagerly because the dispatcher
 * outlives any one request: every subscriber and the dedicated LISTEN connection
 * live in this scope and are torn down together on shutdown.
 */
export const createTurnEventDispatcher = (
  dependencies: TurnEventDispatcherDependencies,
): TurnEventDispatcher => {
  const scope = Effect.runSync(Scope.make());
  const fanouts = new Map<string, TurnFanout>();

  startNotificationListener(scope, fanouts, dependencies);

  const subscribe = (input: {
    readonly assistantTurnId: string;
    readonly authContext: AuthContext;
  }): Promise<TurnEventSubscription> =>
    Effect.runPromise(registerSubscriber(fanouts, dependencies, input));

  const shutdown = (): Promise<void> =>
    Effect.runPromise(Scope.close(scope, Exit.succeed(undefined)));

  return { subscribe, shutdown };
};

/**
 * Fork the one listener that turns notifications into log reads and fan-out.
 *
 * The drain runs in the dispatcher scope, so closing the scope interrupts it and
 * the db notification source tears its dedicated LISTEN connection down. The
 * source already excludes its connection scope from the stream type, so the drain
 * needs no extra scope wiring here.
 */
const startNotificationListener = (
  scope: Scope.Scope,
  fanouts: Map<string, TurnFanout>,
  dependencies: TurnEventDispatcherDependencies,
): void => {
  const drain = Stream.runForEach(
    dependencies.notificationSource.notifications,
    (notification) =>
      reconcileTurn(fanouts, dependencies.ports, notification.assistantTurnId),
  );
  Effect.runSync(Effect.forkIn(drain, scope));
};

/**
 * Register one subscriber, creating the turn's fan-out on first interest.
 *
 * The queue drops under load by design (see `SUBSCRIBER_QUEUE_CAPACITY`); the
 * subscription stream re-syncs from the log on its safety poll, so a dropped
 * signal only delays, never loses, an event.
 */
const registerSubscriber = (
  fanouts: Map<string, TurnFanout>,
  dependencies: TurnEventDispatcherDependencies,
  input: {
    readonly assistantTurnId: string;
    readonly authContext: AuthContext;
  },
): Effect.Effect<TurnEventSubscription> =>
  Effect.gen(function* () {
    const queue = yield* Queue.dropping<SidechatStreamEvent>(
      SUBSCRIBER_QUEUE_CAPACITY,
    );
    const fanout = ensureFanout(
      fanouts,
      input.assistantTurnId,
      input.authContext,
    );
    fanout.subscribers.add(queue);

    yield* recordSubscriberChange(
      dependencies,
      input.assistantTurnId,
      "subscriber_attached",
      fanout,
    );

    return {
      events: queue,
      release: () =>
        Effect.runPromise(
          releaseSubscriber(
            fanouts,
            dependencies,
            input.assistantTurnId,
            queue,
          ),
        ),
    };
  });

const ensureFanout = (
  fanouts: Map<string, TurnFanout>,
  assistantTurnId: string,
  authContext: AuthContext,
): TurnFanout => {
  const existing = fanouts.get(assistantTurnId);
  if (existing) return existing;

  const created: TurnFanout = {
    authContext,
    highWaterMark: -1,
    subscribers: new Set(),
  };
  fanouts.set(assistantTurnId, created);
  return created;
};

/**
 * Remove one subscriber and drop the fan-out when it was the last.
 *
 * Shutting the queue down unblocks the subscription stream draining it; dropping
 * the empty fan-out stops future notifications for this turn from doing any work
 * until a new subscriber registers and re-reads the log.
 */
const releaseSubscriber = (
  fanouts: Map<string, TurnFanout>,
  dependencies: TurnEventDispatcherDependencies,
  assistantTurnId: string,
  queue: Queue.Queue<SidechatStreamEvent>,
): Effect.Effect<void> =>
  Effect.gen(function* () {
    const fanout = fanouts.get(assistantTurnId);
    if (fanout) {
      fanout.subscribers.delete(queue);
      yield* recordSubscriberChange(
        dependencies,
        assistantTurnId,
        "subscriber_detached",
        fanout,
      );
      if (fanout.subscribers.size === 0) fanouts.delete(assistantTurnId);
    }
    yield* Queue.shutdown(queue);
  });

/**
 * Record one subscriber attach/detach with the resulting live subscriber count.
 *
 * The count is the per-instance live fan-out size after the change, so operators
 * can watch subscriber churn per turn. Telemetry is best-effort: the recorder
 * swallows sink failures, so this never affects subscribe/release control flow.
 */
const recordSubscriberChange = (
  dependencies: TurnEventDispatcherDependencies,
  assistantTurnId: string,
  lifecycleState: "subscriber_attached" | "subscriber_detached",
  fanout: TurnFanout,
): Effect.Effect<void> =>
  recordResumableObservation({
    sink: dependencies.observability,
    lifecycleState,
    assistantTurnId,
    requestId: assistantTurnId,
    now: dependencies.ports.clock.now(),
    attributes: { subscriberCount: fanout.subscribers.size },
  });

/**
 * Read rows appended since the high-water mark and fan them out once.
 *
 * Reading once per turn (not once per subscriber) keeps the log read efficient
 * when many sockets watch one turn. A read failure is swallowed: the durable log
 * is unchanged and each subscriber's safety poll will retry, so a transient read
 * error must not fault the shared listener fiber.
 */
const reconcileTurn = (
  fanouts: Map<string, TurnFanout>,
  ports: StreamChatPorts,
  assistantTurnId: string,
): Effect.Effect<void> =>
  Effect.gen(function* () {
    const fanout = fanouts.get(assistantTurnId);
    if (!fanout) return;

    const events = yield* readNewEvents(ports, fanout, assistantTurnId);
    for (const event of events) {
      fanout.highWaterMark = Math.max(fanout.highWaterMark, event.sequence);
      offerToSubscribers(fanout, event);
    }
  });

const readNewEvents = (
  ports: StreamChatPorts,
  fanout: TurnFanout,
  assistantTurnId: string,
): Effect.Effect<readonly SidechatStreamEvent[]> =>
  ports.turnEventLog
    .readEventsAfter({
      authContext: fanout.authContext,
      assistantTurnId,
      after: fanout.highWaterMark,
    })
    .pipe(
      Effect.catchCause(() =>
        Effect.succeed([] as readonly SidechatStreamEvent[]),
      ),
    );

const offerToSubscribers = (
  fanout: TurnFanout,
  event: SidechatStreamEvent,
): void => {
  for (const queue of fanout.subscribers) {
    // Non-blocking: a full (lagging) subscriber drops the signal and re-syncs
    // from the durable log on its next safety poll.
    Queue.offerUnsafe(queue, event);
  }
};
